### ISSUE TITLE
本软件是否支持代理模式？

### ISSUE THREAD

**Issue by qq86007801** [PerrorOne/miner-proxy#1]
类似一个代理网关的模式，，从代理客户端到服务端，只有一个TCP连接，进行任务分发，这样能大幅度降低带宽的占用，类似另一个minerproxy软件一样

**Comment by PerrorOne** [comment]
没有的目前只是一个简单的tcp加密代理功能, 每个矿机都会打开一个tcp连接, 对于内核抽水的tcp连接我直接禁止掉了.

**Comment by 15868153548** [comment]
> 没有的目前只是一个简单的tcp加密代理功能, 每个矿机都会打开一个tcp连接, 对于内核抽水的tcp连接我直接禁止掉了.
请问这个“内核抽水的tcp，直接禁止了”。这个是在代码哪里体现的呢？能否截图告知，谢谢

**Comment by PerrorOne** [comment]
> > 没有的目前只是一个简单的tcp加密代理功能, 每个矿机都会打开一个tcp连接, 对于内核抽水的tcp连接我直接禁止掉了.
> > 请问这个“内核抽水的tcp，直接禁止了”。这个是在代码哪里体现的呢？能否截图告知，谢谢
这个禁止内核抽水直连需要你自己去禁止, 比如使用iptables命令禁止掉除了代理的ip出入规则
