### ISSUE TITLE
总是频繁出现runtime error

### ISSUE THREAD

**Issue by coolman888** [PerrorOne/miner-proxy#10]
runtime error: slice bounds out of range [:-11]
goroutine 120 [running]:
runtime/debug.Stack(0x4e9f8c, 0xc000082000, 0x2)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
miner-proxy/pkg.Recover(0xc0000f5b01)
        /home/miner-proxy/pkg/recover.go:12 +0x84
panic(0x644ec0, 0xc0000f5da0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
miner-proxy/proxy.(*Proxy).DecryptData(0xc0000be240, 0xc0001df7e8, 0x1, 0x8, 0x4bf43c, 0xc000012700, 0xc0001df7e5, 0x1, 0x1)
        /home/miner-proxy/proxy/proxy.go:197 +0x185
miner-proxy/proxy.(*Proxy).connRemote.func1(0x1, 0xc0001df7e8, 0x1, 0x8)
        /home/miner-proxy/proxy/proxy.go:293 +0x7a
miner-proxy/proxy.(*Package).Read(0xc000033e10, 0x6a9880, 0xc000010068, 0xc0000e5df8, 0xc000010068, 0x10000c00009f180)
        /home/miner-proxy/proxy/package.go:160 +0x1fd
miner-proxy/proxy.(*Proxy).connRemote(0xc0000be240, 0x0, 0x0, 0xc0001a2e00, 0xc0001d90f8)
        /home/miner-proxy/proxy/proxy.go:292 +0x612
miner-proxy/proxy.(*Proxy).Start(0xc0000be240)
        /home/miner-proxy/proxy/proxy.go:86 +0x103
created by main.(*proxyService).run
        /home/miner-proxy/cmd/miner-proxy/main.go:89 +0x6e9

**Comment by PerrorOne** [comment]
服务端和客户端能否贴一下?

**Comment by coolman888** [comment]
服务端： miner-proxy -l 0.0.0.0:8888 -r 矿池IP:8888 -secret_key 12345678 -sc
客户端： miner-proxy -l 0.0.0.0:8888 -r 中转服务器IP:8888 -secret_key 12345678 -client -sc

**Comment by PerrorOne** [comment]
是服务端报错还是客户端?
