### ISSUE TITLE
有没有一种可能，就像墙检测ss和ssr一样，检测到你全走加密流量，特征符合ss和ssr，就当你翻墙给你封了

### ISSUE THREAD

**Issue by LiuTangLei** [PerrorOne/miner-proxy#17]
这个项目会不会也有特殊的特征，最后加密完还是被检测出来了，能不能密上密，比如在加密的基础上，走类似于trojan那样的tls加密，走https，看起来就像在访问网站，特征就不好检测出来了

**Comment by PerrorOne** [comment]
特征肯定是有的, 封包解包就必须要这些特征, 目前有了解到的就是将协议更换成常见软件协议, 比如mysql/redis/rpc协议

**Comment by LiuTangLei** [comment]
了解
