### ISSUE TITLE
请问这款软件 抽水吗

### ISSUE THREAD

**Issue by gakaki** [PerrorOne/miner-proxy#22]
**描述错误**
清晰简洁地描述错误是什么。

**重现**
重现行为的步骤：
1. xxx
2. xxx

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**您的系统信息**
 - 系统名称:  win
 - 系统版本: 10

**miner-proxy信息**
 - 版本:  v0.4.0 或者 填写 启动时输出的 "版本日志:"

**Comment by Kayuii** [comment]
看代码现在没有这个功能

**Comment by PerrorOne** [comment]
没有抽水

**Comment by our198** [comment]
可以加上自定义抽水，还有拦截内核抽水为作者钱包，这样作者也不能完全免费开发吧，本来内核都要抽水的
