### ISSUE TITLE
客户端一直提示正在打包

### ISSUE THREAD

**Issue by miner1888** [PerrorOne/miner-proxy#25]
等了半个小时了 客户端还在打包。。。
我这边网络也不慢 从github 下载别的软件 100M也就几秒钟 这个客户端一直下载不下来
还有这个是只能代理ETH 还是所有币种都能代理

**Comment by PerrorOne** [comment]
你的版本是什么?
所有币种都可以代理

**Comment by our198** [comment]
客户端必须直连到服务端，不然你怎么解密数据，然后服务端才可以连矿池
