### ISSUE TITLE
V0.5.4 频繁发生链接断开错误

### ISSUE THREAD

**Issue by workboy** [PerrorOne/miner-proxy#27]
客户端 message:miner close connection error: EOF. close connection
服务端read data from miner pool error read tcp 172.31.40.48:40074->172.65.231.156:4444 use of closed network connection 
服务器追踪地址至矿池 没有发生过丢包 ping 2.4 ms，客户端至服务端 没有发生丢包  ping 40 ms

**Comment by workboy** [comment]
服务器linux安装命令 
./miner-proxy_linux_amd64 -l :4333 -k "test112233" -p "test112233" install
客户端windows命令
.\miner-proxy_windows_amd64.exe -k test112233 -r XX.XX.XX.XX:4333 -l :6666,:7777 -c -u asia1.ethermine.org:4444,asia1.ethermine.org:14444

**Comment by PerrorOne** [comment]
暂时可以用0.4以及以下版本
