### ISSUE TITLE
有一些能够增强使用的功能, 是否能够支持?

### ISSUE THREAD

**Issue by fang-aunt** [PerrorOne/miner-proxy#3]
1. 可以在客户端指定连接那个矿池
2. 支持交互式的安装引导
3. 可以用参数指定每多少个字符插入混淆字符
4. 支持流量异常告警?

**Comment by 15868153548** [comment]
我们一起开发吧

**Comment by PerrorOne** [comment]
最近没有

> 我们一起开发吧

最近没有更新是在准备重构, 之前基于别人的转发代码在master分支也都去除了, 想把这个代理做成分层:
第一层tcp/udp协议实现
第二层就是代理协议比如openvpn/socks5协议等等
目前来看工作量还算是蛮大的, 不过我还没有构思好, 再加上最近工作有点忙

**Comment by chenglianggege** [comment]
可刑可铐

**Comment by PerrorOne** [comment]
> 1. 可以在客户端指定连接那个矿池
> 2. 支持交互式的安装引导
> 3. 可以用参数指定每多少个字符插入混淆字符
> 4. 支持流量异常告警?

可以在客户端指定连接那个矿池 目前已经支持

**Comment by bihaiwangba** [comment]
我vps代理服务安装成功，客户端也安装成功，但是矿池地址填写vps  ip地址和vps本地端口，提示无法连接矿池
