### ISSUE TITLE
服务端不能加ssl:

### ISSUE THREAD

**Issue by pupuisok** [PerrorOne/miner-proxy#8]

**Comment by pupuisok** [comment]
阿里的云，所以保险一点，想转发e池的5555ssl端口
服务端转发地址ssl://asia2.ethermine.org:5555
会提示不允许多的冒号

**Comment by PerrorOne** [comment]
直接填写 `asia2.ethermine.org:5555`

**Comment by pupuisok** [comment]
服务端好像是解密以后以tcp发送的，我用阿里云，解密后发给矿池的数据会被抓包吗

**Comment by PerrorOne** [comment]
ssl是在tcp上层的协议, 所有http/https/ssl协议都是通过tcp发送的
另外建议不要使用阿里云, 如果非要使用阿里云可以使用下面的配置:
矿机 -> 转发客户端 -> 阿里云(端口转发) -> 其他云服务器(转发服务端端) -> 矿池

**Comment by pupuisok** [comment]
未来有可能加入以解密以后以ssl发送吗

**Comment by PerrorOne** [comment]
则取决与你在服务端/客户端设置的矿池连接, 如果该连接是 ssl那么就是用ssl发送的, 如果没有ssl加密就不会用ssl加密

**Comment by pupuisok** [comment]
矿机肯定是tcp的了，比如我自己矿机tcp，经过你的加密后，连到阿里云的服务端，解密后，现在是通过明文tcp发送去矿池，有没有可能后期加上，解密后再套一层ssl发送区矿池，第一次弄不太懂，买了1年的阿里云

**Comment by PerrorOne** [comment]
你选择的矿池连接是ssl吗?, 如果是那么 矿机 -> 客户端 是ssl, 服务端 -> 矿池 也是ssl

**Comment by pupuisok** [comment]
我最终的目的矿池，就是这个ssl://asia2.ethermine.org:5555，是e池的5555端口，协议走的是ssl，
本地地址已经改成127了，这个127，应该是tcp吧？

**Comment by pupuisok** [comment]
关键就是，光机到客户端，不是走的127么，怎么走ssl

**Comment by PerrorOne** [comment]
tcp相当于一个管道, ssl相当于管道中的物品,    而矿机和矿池相当于管道的出入口,   中间管道传输的物品, 取决于 管道入口 行的物品是什么, 如果管道入口放的的物品是ssl, 整条管道(矿机 -> 客户端 ->服务端 -> 矿池)传输都是ssl

**Comment by pupuisok** [comment]
大佬有tg吗，学习交流下，有偿

**Comment by PerrorOne** [comment]
新建了一个Q群:  538528847
