### ISSUE TITLE
linux端频繁增加连接数据

### ISSUE THREAD

**Issue by dreamlog** [PerrorOne/miner-proxy#9]
目前只有一台windows在连接服务端，轻松矿工显示连接断开，重新登录，然后服务端的连接数量就频繁增加了，不知道这是不是bug，会不会引起性能问题。

**Comment by PerrorOne** [comment]
不会引发性能, 服务端日志显示的`当前在线 n 个客户端`私有bug的, windows端你要不试试ping一下你的服务端ip看看会不会出现ping不通的结果.
可以运行 ping 服务端ip/ping -t 服务端

**Comment by dreamlog** [comment]
谢谢，我试试

**Comment by PerrorOne** [comment]
![image](https://user-images.githubusercontent.com/23651751/148632098-28038590-cb8f-41bb-873e-0eb855b39d93.png)
这是我自己服务端的日志, 本地网络到服务端没有问题的话, 基本上是不会出现重复断开的

**Comment by dreamlog** [comment]
好的，用的池子是stratum.okpool.me，问题应该是出在这个池子会不定时的连接不上，我换一个池子再试试，谢谢大佬。
这是我的服务端日志：
Jan 08 05:00:46 ip-172-31-17-237 miner-proxy_linux_amd64[105298]: 2022/01/08 05:00:46 从 2022-01-08 03:54:16 至现在总计加密转发 2.4 MB 数据; 平均转发速度 602 B/秒; 当前在线 3 个客户端
Jan 08 05:00:51 ip-172-31-17-237 miner-proxy_linux_amd64[105298]: 2022-01-08 05:00:51 connection x.x.x.x:58885>> 读取明文, 发送加密数据 error write tcp 172.31.17.237:13336->x.x.x.x:58885: write: connection timed out
Jan 08 05:00:51 ip-172-31-17-237 miner-proxy_linux_amd64[105298]: 2022-01-08 05:00:51 connection x.x.x.x:58885>> Closed (0 bytes sent, 0 bytes recieved)
Jan 08 05:01:16 ip-172-31-17-237 miner-proxy_linux_amd64[105298]: 2022/01/08 05:01:16 从 2022-01-08 03:54:16 至现在总计加密转发 2.4 MB 数据; 平均转发速度 601 B/秒; 当前在线 2 个客户端
Jan 08 05:01:46 ip-172-31-17-237 miner-proxy_linux_amd64[105298]: 2022/01/08 05:01:46 从 2022-01-08 03:54:16 至现在总计加密转发 2.4 MB 数据; 平均转发速度 602 B/秒; 当前在线 2 个客户端

**Comment by PerrorOne** [comment]
我用的是E池, 一直很稳定
